### PR TITLE
Update Config.java

### PR DESCRIPTION
**Pull request by peevdimitar**
Integer.getInteger(runId) should be Integer.parseInt(runId) as we need to pass the runId passed through environment variable. Please review the getRunId() method.
getInteger()  - Determines the integer value of the system property with the specified name
parseInt() - Parses the string argument as a signed decimal integer

### CODE REVIEW

**Comment by atodorov** [comment]
@peevdimitar can you explain what were you trying to do and why did you close this PR ?

**Comment by peevdimitar** [comment]
@atodorov I assume the TCMS_RUN_ID has to be passed as  the rest of the environment variables. 

**For example:** 
TCMS_API_URL=http://sample-url.com/xml-rpc/
TCMS_USERNAME=test-user
TCMS_PASSWORD=test-pass
TCMS_PRODUCT=TestProject
TCMS_PRODUCT_VERSION=1.0.0
TCMS_RUN_ID=429

If we use the environment variables as the example above. The method getRunId() will always return "null" which means that the method getTestRunId() will always create new test run. From my comment above you can see that if we change  Integer.getInteger(runId) in the method getRunId() to Integer.parseInt(runId) should fix the issue. Again only if we pass TCMS_RUN_ID as integer as shown in the example above.

```    
public Integer getRunId() {
        String runId = System.getenv("TCMS_RUN_ID");
        if (runId == null) {
            return null;
        } else {
            return Integer.getInteger(runId);
        }
    }
```

```
    public int getTestRunId() {
        if (runId == null) {
            Integer testRun = config.getRunId();
            if (testRun != null) {
                runId = client.getRun(testRun).getId();
            }

//TODO: this must check if this TR is already available in the DB
// and not create a new TR for the same product, version and build
            if (runId == null) {
                runId = client.createNewRun(getBuild(getProductId()),
                        config.getUsername(),
                        getPlanId(),
                        String.format("[JUnit] Results for %s, %s, %s",
                                config.getProduct(),
                                config.getProductVersion(),
                                config.getBuild())).getId();
            }
        }
        casesInTestRun = client.getRunIdTestCases(runId);
        return runId;
    }
```

FYI: It seems that the casesInTestRun variable in method getTestRunId() is not being used and the request client.getRunIdTestCases(runId) is not needed.

**Comment by atodorov** [comment]
> FYI: It seems that the casesInTestRun variable in method getTestRunId() is not being used and the request client.getRunIdTestCases(runId) is not needed.

Not quite: 

```
$ grep casesInTestRun * -R
main/java/org/kiwitcms/java/junit/TestDataEmitter.java:    private TestCase[] casesInTestRun;
main/java/org/kiwitcms/java/junit/TestDataEmitter.java:        casesInTestRun = client.getRunIdTestCases(runId);
main/java/org/kiwitcms/java/junit/TestDataEmitter.java:// TODO: this method should accept casesInTestRun and not call RPC if the TestCase
```

but this is a separate issue.

**Comment by atodorov** [comment]
@peevdimitar indeed it looks like `Integer.getInteger()` should be replaced by `Integer.parseInt()`. You will have to open a new PR with your previous changes and we can work from there.

A unit test to demonstrate the failure would be a nice way to start.

**Pull request closed without merging**
